/// Rwandan District → Sectors for guest checkout location selectors.
abstract final class RwandaLocations {
  static const Map<String, List<String>> districts = {
    'Gasabo': [
      'Remera',
      'Kimironko',
      'Kacyiru',
      'Gisozi',
      'Bumbogo',
      'Jabana',
      'Nduba',
      'Gatsata',
      'Gikomero',
      'Jali',
      'Kinyinya',
      'Ndera',
      'Rusororo',
      'Rutunga',
      'Kanombe',
    ],
    'Kicukiro': [
      'Gatenga',
      'Gikondo',
      'Kagarama',
      'Kanombe',
      'Kicukiro',
      'Kigarama',
      'Masaka',
      'Niboye',
      'Nyarugunga',
      'Gahanga',
    ],
    'Nyarugenge': [
      'Nyamirambo',
      'Nyarugenge',
      'Muhima',
      'Rwezamenyo',
      'Kimisagara',
      'Gitega',
      'Kanyinya',
      'Kigali',
      'Mageragere',
      'Nyakabanda',
    ],
    'Bugesera': [
      'Gashora',
      'Juru',
      'Kamabuye',
      'Ntarama',
      'Nyamata',
      'Rilima',
      'Ruhuha',
      'Shyara',
    ],
    'Rwamagana': [
      'Fumbwe',
      'Gahengeri',
      'Gishari',
      'Karenge',
      'Kigabiro',
      'Muhazi',
      'Munyaga',
      'Munyiginya',
      'Musha',
      'Muyumbu',
      'Mwulire',
      'Nyakaliro',
      'Nzige',
      'Rubona',
    ],
    'Musanze': [
      'Busogo',
      'Cyuve',
      'Gacaca',
      'Gashaki',
      'Gataraga',
      'Kimonyi',
      'Kinigi',
      'Muhoza',
      'Muko',
      'Musanze',
      'Nkotsi',
      'Nyange',
      'Remera',
      'Rwaza',
      'Shingiro',
    ],
    'Huye': [
      'Gishamvu',
      'Huye',
      'Karama',
      'Kigoma',
      'Kinazi',
      'Maraba',
      'Mbazi',
      'Mukura',
      'Ngoma',
      'Ruhashya',
      'Rusatira',
      'Rwaniro',
      'Simbi',
      'Tumba',
    ],
    'Rubavu': [
      'Bugeshi',
      'Busasamana',
      'Cyanzarwe',
      'Gisenyi',
      'Kanama',
      'Kanzenze',
      'Mudende',
      'Nyakiliba',
      'Nyamyumba',
      'Nyundo',
      'Rubavu',
      'Rugerero',
    ],
  };

  static List<String> get districtNames => districts.keys.toList()..sort();

  static List<String> sectorsFor(String district) =>
      List<String>.from(districts[district] ?? const []);
}
